services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python
    command: uvicorn app:app --host 0.0.0.0 --reload 
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - PYTHONPATH=/app

networks:
  app-network:
    external: true
    driver: bridge
