services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
      - ./venv/:/usr/src/app/venv
    #entrypoint: ["./venv/bin/uvicorn"]
    #command: [ "app:app", "--host", "0.0.0.0", "--port", "8000", "--reload" ]
    environment:
      - FASTAPI_APP=app:app
      - ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
