services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: uvicorn app:app --host 0.0.0.0
    volumes:
      - .:/app
    ports:
      - 8008:8000
    networks:
      - app-network

networks:
  app-network:
    driver: bridge