services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python
    command: uvicorn app:app --host 0.0.0.0 --reload 
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    networks:
      - app-network
    environment:
      - WATCHFILES_FORCE_POLLING=true
      - PYTHONPATH=/app

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8001:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_PORT=8000
    volumes:
      - chroma_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  chroma_data: