services:
  python:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: python
    ports:
      - "8000:8000"
    volumes:
      - ./:/usr/src/app
    command: uvicorn app:app --host 0.0.0.0 --reload
    environment:
      - FASTAPI_APP=app:app
      - ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
    
